### ISSUE TITLE
Does not call callback when app is closed

### ISSUE THREAD

**Issue by Kurosawa7** [caffeinalab/ti.goosh#99] opened 2018-02-06 05:55 UTC
When the application is closed, tap the notification banner to open the application.
However, callback will not be called.
For this reason, we are in trouble because we can not process when the application opens after receiving notification.

This was done with an old version.

Is there a way?
Thank you.

**Comment by progress44** [comment] 2018-02-06 11:35
This is a duplicate of issue #55

**Closed by progress44** 2018-02-06 11:35 UTC
Labels: duplicate
