### ISSUE TITLE
Not getting callback when the app is in background or killed

### ISSUE THREAD

**Issue by nrpverma** [caffeinalab/ti.goosh#117] opened 2018-11-26 09:05 UTC
Module is working so far, Notifications arrive in the app via GCM when the app is running in the foreground and pop up as a notification when the app is in the background not getting the payload

Ti sdk :7.4.0 GA
Device's Android Version: 8.1.0
Ti.goosh: v 4.1.1

Thanks

**Comment by nrpverma** [comment] 2018-11-26 09:09
[WARN] :   W/ti.goosh.IntentService: Show Notification: FALSE
[INFO] :   {"data":"{\"c.i\": \"null\"}","inBackground":false}
[INFO] :   GCMIntentService: (IntentService[GCMIntentService--1]) [4,158634] Title: test 12
[INFO] :   GCMIntentService: (IntentService[GCMIntentService--1]) [0,158634] Message: test
[INFO] :   GCMIntentService: (IntentService[GCMIntentService--1]) [0,158634] Ticker: null

Above payload getting when the app in the foreground.

**Comment by Hemantsolanki103** [comment] 2018-11-26 09:46
Hi,

Please send data as per below format.

{"to":['your device token'],
"data":{
"data":{
"title":"abc",
"alert":"abc",
"badge":2
}
}
}
let me know if any issue.

**Comment by nrpverma** [comment] 2018-11-26 10:52
Thnks ill try. but when the app is in background or killed not getting callback please help for the same?

**Comment by nrpverma** [comment] 2018-11-26 11:18
@Hemantsolanki103 why there is two data object?

"data":{
"data":{

?

**Comment by Hemantsolanki103** [comment] 2018-11-26 11:24
Please tell me, you are getting notification when your app in background or quit from background?

As per documentation of module, I have sent two json under json. And as per your question you are getting "{"data":"**{"c.i": "null"}**","inBackground":false}" but you should get proper json in data json object. So that is the reason you have to sent data as a given solution.

**Comment by nrpverma** [comment] 2018-11-26 12:13
no, I m not getting the notification in status bar.

**Comment by Hemantsolanki103** [comment] 2018-11-26 12:20
Please download module from below link and replace your module and run application.

Please send data as per given format or you can try with one data json object also.

[ti.goosh.zip](https://github.com/caffeinalab/ti.goosh/files/2615433/ti.goosh.zip)

Please let me know, if any issue again. If you will get any issue again, provide all details like device/emulator version, Ti SDK and CLI version

**Comment by nrpverma** [comment] 2018-11-26 12:47
Device's Android Version : Moto G5 Plus/v8.1.0

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 8589934592
Node.js
  Node.js Version             = 8.9.1
  npm Version                 = 6.4.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = 7.4.0.GA
  SDK Path                    = /Users/Library/Application Support/Titanium/mobilesdk/osx/7.4.0.GA
  Target Platform             = android

**Comment by Hemantsolanki103** [comment] 2018-11-26 12:53
Have you replace module which is provided to  you? I think it should work.

**Comment by nrpverma** [comment] 2018-11-26 13:17
yes, i replaced the module with urs. 

yes already intialzed this in tiapp.xml:
<property name="ti.goosh.defaultChannel">CHANNEL NAME</property>

**Comment by Jei** [comment] 2018-11-26 13:31
We've just released a new version of Ti.Goosh that should solve this problem. You can find it [here](https://github.com/caffeinalab/ti.goosh/releases/tag/v4.2.0).
I'm closing this issue as it is a duplicate of #114. If you still have the same problem with Ti.Goosh 4.2.0, you can use that thread.

**Closed by Jei** 2018-11-26 13:31 UTC

**Comment by nrpverma** [comment] 2018-11-27 05:37
@Hemantsolanki103 
i configured as per urs, but still the same issue

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  CPUs                      = 4
  Memory                      = 8589934592
Node.js
  Node.js Version             = 8.9.4
  npm Version                 = 5.6.0
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = 7.4.1.GA
  SDK Path                    = /Users/Library/Application Support/Titanium/mobilesdk/osx/7.4.1.GA
  Target Platform             = android

**Comment by Hemantsolanki103** [comment] 2018-11-27 06:02
Hi,

How you are sending push notification to device?
Like via pushtry.com or directly from admin?

At my end I got same issue but I replaced module  and send payload whatever
gave you. It was working fine either in device or emulator.

Please update me as per above scenario so we think for another solution.

**Comment by nrpverma** [comment] 2018-11-27 06:06
I'm using admin portal for the push notification.

i have changed the payload as you suggested but small changes removed the nested data object.

{"to":['your device token'],
"data":{
"title":"abc",
"alert":"abc",
"badge":2
}
}

**Comment by Hemantsolanki103** [comment] 2018-11-27 06:13
Give me 30mnt I'll share my POC for help.

**Comment by nrpverma** [comment] 2018-11-27 06:39
ok, let me try.

**Comment by Hemantsolanki103** [comment] 2018-11-27 06:42
I am sure if you send payload correctly, your problem will resolved.
 If you will not get success again then I try to send my POC application from other medium.

**Comment by nrpverma** [comment] 2018-11-27 07:10
Yes, now i m getting payload. but with the error.

[INFO] :   Succes data {"data":"{\"alert\":\"your message\",\"title\":\"Working Good\"}","inBackground":false}
[ERROR] :  V8Exception: Exception occurred at undefined:1: Uncaught SyntaxError: Unexpected end of JSON input

**Comment by nrpverma** [comment] 2018-11-27 07:12
I got the above payload when the app is in the foreground.

**Comment by Hemantsolanki103** [comment] 2018-11-27 07:13
Great,
Please share your callback function where you handle your payload.
Second try in background mode.

**Comment by nrpverma** [comment] 2018-11-27 07:18
I tried in the background. nothing is happening.

**Comment by Hemantsolanki103** [comment] 2018-11-27 07:20
Please share your callback function where you handle your payload.
First we resolved your error

**Comment by nrpverma** [comment] 2018-11-27 07:40
yes, got resolved, when the app is in the foreground. 
but the notification not getting when the app is in the background or killed.

**Comment by Hemantsolanki103** [comment] 2018-11-27 07:48
[PushTest.zip](https://github.com/caffeinalab/ti.goosh/files/2618799/PushTest.zip)

Please check working POC application for all API level device.
Working Mode: Background and Foreground

**Comment by nrpverma** [comment] 2018-11-27 08:19
@Hemantsolanki103, i build ur provided app in my device using my sender id. I sent notification using http://pushtry.com/.
i got the payload in the foreground, but when the app got killed didn't receive the notification on status bar.

**Comment by Hemantsolanki103** [comment] 2018-11-27 09:07
I get push when application quit accord to below scenario.
First send one notification in foreground and then quit application and send push.

**Comment by Hemantsolanki103** [comment] 2018-11-27 09:16
With Module : 4.2.0

Scenario: when application launch and quit from background and send push notification, push not come but you launch the application then push previous push will come.

Please check once.
