### ISSUE TITLE
Failed to package due to duplicate png assets in 3.0.0

### ISSUE THREAD

**Issue by amigoni** [caffeinalab/ti.goosh#84] opened 2017-10-18 14:24 UTC
[ERROR] :  Failed to package application:
[ERROR] :  
[ERROR] :  /Users/Leonardo/Documents/Appcelerator_Studio_Workspace/Fluid/build/android/res/drawable-hdpi-v4/common_full_open_on_phone.png: error: Duplicate file.
[ERROR] :  /Users/Leonardo/Documents/Appcelerator_Studio_Workspace/Fluid/build/android/res/drawable-hdpi/common_full_open_on_phone.png: Original is here. The version qualifier may be implied.

**Comment by furthurr** [comment] 2017-10-18 15:33
hi .... the same error 


`[ERROR] /Users/pedrogomezvasquez/Documents/repositorios/cleanect/Codigos/Weklin/build/android/res/drawable-xhdpi/common_full_open_on_phone.png: error: Duplicate file.
[ERROR] /Users/pedrogomezvasquez/Documents/repositorios/cleanect/Codigos/Weklin/build/android/res/drawable-xhdpi-v4/common_full_open_on_phone.png: Original is here. The version qualifier may be implied.`

**Comment by progress44** [comment] 2017-10-20 14:22
Hi, @amigoni @furthurr 
We had the same error and for the time being we resolved it by removing the image defined as a duplicate. It enables us to build the app and everything works smoothly. This is a temporary fix until we find the cause for this. We found it to be in `ti.map` and it is also included in the `goole-play-services-base.aar` unless you want to explode the .aar and remove the file, it would be easier to remove it from the `ti.map` module.
Let me know how it goes

**Comment by takhil** [comment] 2017-12-29 23:22
/Users/akhiltirumalasetty/build/android/res/drawable-xhdpi/common_full_open_on_phone.png: error: Duplicate file.
[ERROR] :  /Users/akhiltirumalasetty//build/android/res/drawable-xhdpi-v4/common_full_open_on_phone.png: Original is here. The version qualifier may be implied.

using 6.3.0 GA  how to solve this ?

**Comment by progress44** [comment] 2018-01-11 11:17
This was fixed in version 3.0.3

**Closed** 2018-01-11 11:18 UTC
