### ISSUE TITLE
Android Oreo Issue --Notification is not receiving in background

### ISSUE THREAD

**Issue by Hemantsolanki103** [caffeinalab/ti.goosh#116] opened 2018-11-19 12:30 UTC
Hi,
Notification is not receiving in background on Oreo android devices.

If anyone has some relevant solution, please let me know.

Version: 4.1.1
Tested SDK: 7.4.0/7.4.1

Thanks & Regards,
Hemant Solanki

**Comment by furthurr** [comment] 2018-11-20 23:53
https://github.com/caffeinalab/ti.goosh/issues/114#issuecomment-436813556

**Comment by Hemantsolanki103** [comment] 2018-11-21 10:11
@furthurr : Thanks for your great help.

**Comment by Jei** [comment] 2018-11-26 13:32
We've just released a new version of Ti.Goosh that should solve this problem. You can find it [here](https://github.com/caffeinalab/ti.goosh/releases/tag/v4.2.0).
I'm closing this issue, since it's a duplicate of #114.

**Closed by Jei** 2018-11-26 13:32 UTC
